package cc

import (
	"crypto/rand"
	"encoding/base64"
	"sync"
	"time"
)

// DefaultStateTTL governs how long an OAuth state token stays valid
// before Consume rejects it. Five minutes matches CC Studio's own
// auth-prompt timeout.
const DefaultStateTTL = 5 * time.Minute

// StateStore tracks unconsumed OAuth state tokens. CSRF-only — we never
// store anything user-identifying beyond the token's existence and
// expiry.
type StateStore struct {
	mu    sync.Mutex
	items map[string]time.Time
	ttl   time.Duration
	now   func() time.Time
}

// NewStateStore returns an empty store. ttl ≤ 0 falls back to
// DefaultStateTTL.
func NewStateStore(ttl time.Duration) *StateStore {
	if ttl <= 0 {
		ttl = DefaultStateTTL
	}
	return &StateStore{
		items: make(map[string]time.Time),
		ttl:   ttl,
		now:   time.Now,
	}
}

// Generate returns a new random state token (32 bytes, base64url
// encoded, ~43 chars) and records its creation time.
func (s *StateStore) Generate() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	tok := base64.RawURLEncoding.EncodeToString(b)
	s.mu.Lock()
	defer s.mu.Unlock()
	s.gcLocked()
	s.items[tok] = s.now()
	return tok, nil
}

// Consume returns true if tok was generated by this store, has not
// expired, and has not been used. Tokens are single-shot: Consume
// removes them on hit.
func (s *StateStore) Consume(tok string) bool {
	if tok == "" {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.gcLocked()
	created, ok := s.items[tok]
	if !ok {
		return false
	}
	delete(s.items, tok)
	return s.now().Sub(created) < s.ttl
}

// Len reports how many unexpired tokens are tracked. Exposed for tests
// and dashboard diagnostics.
func (s *StateStore) Len() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.gcLocked()
	return len(s.items)
}

func (s *StateStore) gcLocked() {
	cutoff := s.now().Add(-s.ttl)
	for k, t := range s.items {
		if t.Before(cutoff) {
			delete(s.items, k)
		}
	}
}
